---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - unzip

- name: Install Terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip"
    dest: "/tmp/terraform.zip"
  register: terraform_download

- name: Extract Terraform
  unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin"
    remote_src: yes
    copy: no
    creates: "/usr/local/bin/terraform"
  when: terraform_download.changed
