name: Install Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform_install:
    name: Install Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install ansible
    
    - name: Run playbook
      uses: ansible/actions/ansible-runner-action@v2
      with:
        playbook: terraform-install.yml

